name: Trigger workflow
on:
  push:
    branches: [ main ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repository dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
            token: ${{ secrets.PAT }}
            repository: chain-builds/builds
            event-type: dependency_updated
            payload: '{"message": "Hello from another repository"}'        