name: Trigger workflow
on:
  push:
    branches: [ main ]
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow dispatch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.PAT }} # This token must have repo scope
          script: |
            github.repos.createDispatchEvent({
              owner: 'chain-builds',
              repo: 'builds',
              event_type: 'dependency_updated', 
              client_payload: { 
                message: 'Hello from another repository'
              }
            })
